In [1]:
from Neural_Nets.Classification.ThermoClassifier.Development.ThermoClassifier import ThermoClassifier
from Neural_Nets.Classification.ClassificationDataset.Development.ClassificationDataset import *
from torch.utils.data import DataLoader
import torch
import numpy as np

In [2]:
net = ThermoClassifier()

inp = torch.tensor([[[200., 5.]], [[250., 7.]], [[400., 50.]]])

out = net(inp)

C:\Users\danie\anaconda3\envs\5_Programmcodes\lib\site-packages\torch\nn\modules\container.py:141: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)


In [3]:
dc = DatasetCreator(r"C:\Users\danie\Documents\Montanuni\Masterarbeit\4_Daten\Elements.xlsx", elements=None, 
                   splits=(0.6, 0.2, 0.2), validation=True)
train_dataset, test_dataset, val_dataset = dc.get_datasets()

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=1, shuffle=True)

if val_dataset:
    val_loader = DataLoader(val_dataset)

[[[    656.          -32034.65625          0.        ]
  [   1820.         -126104.09375          0.        ]
  [   1085.          -62425.390625         0.        ]
  [   1045.          -59344.234375         0.        ]
  [   1955.         -139020.96875          0.        ]]

 [[    573.          -26941.78515625       0.        ]
  [   1937.         -137280.21875          0.        ]
  [   1616.         -107229.625            0.        ]
  [    765.          -39154.5859375        0.        ]
  [   1445.          -92067.203125         0.        ]]

 [[    777.          -39966.015625         0.        ]
  [   1299.          -79650.0625           0.        ]
  [    620.          -29788.56640625       0.        ]
  [    766.          -39221.984375         0.        ]
  [    487.          -22005.828125         0.        ]]

 ...

 [[   1275.          -77658.78125          0.        ]
  [   1784.         -122715.1875           0.        ]
  [    521.          -23912.78125          0.        

[[[ 1.63000000e+03 -3.73281562e+04  2.70000000e+01]
  [ 1.16800000e+03 -1.99129375e+04  2.70000000e+01]
  [ 1.66200000e+03 -3.86824375e+04  2.70000000e+01]
  [ 8.71000000e+02 -1.11749922e+04  2.70000000e+01]
  [ 1.50900000e+03 -3.23705156e+04  2.70000000e+01]]

 [[ 1.71100000e+03 -4.07899688e+04  2.70000000e+01]
  [ 1.19800000e+03 -2.09118594e+04  2.70000000e+01]
  [ 1.91700000e+03 -5.00790625e+04  2.70000000e+01]
  [ 1.61800000e+03 -3.68249375e+04  2.70000000e+01]
  [ 4.53000000e+02 -3.14348047e+03  2.70000000e+01]]

 [[ 8.11000000e+02 -9.68713281e+03  2.70000000e+01]
  [ 1.15900000e+03 -1.96171719e+04  2.70000000e+01]
  [ 1.39000000e+03 -2.77582031e+04  2.70000000e+01]
  [ 1.44300000e+03 -2.97791406e+04  2.70000000e+01]
  [ 8.97000000e+02 -1.18505703e+04  2.70000000e+01]]

 ...

 [[ 1.66800000e+03 -3.89383125e+04  2.70000000e+01]
  [ 1.49700000e+03 -3.18932812e+04  2.70000000e+01]
  [ 4.40000000e+02 -2.99078516e+03  2.70000000e+01]
  [ 1.96200000e+03 -5.21964062e+04  2.70000000e+01]


[[[ 1.91300000e+03 -1.57839781e+05  4.40000000e+01]
  [ 4.66000000e+02 -2.33014414e+04  4.40000000e+01]
  [ 1.24500000e+03 -8.93663281e+04  4.40000000e+01]
  [ 1.90700000e+03 -1.57192469e+05  4.40000000e+01]
  [ 1.09600000e+03 -7.52782812e+04  4.40000000e+01]]

 [[ 1.05900000e+03 -7.18625781e+04  4.40000000e+01]
  [ 7.66000000e+02 -4.61891562e+04  4.40000000e+01]
  [ 1.11000000e+03 -7.65795938e+04  4.40000000e+01]
  [ 1.78300000e+03 -1.43931922e+05  4.40000000e+01]
  [ 1.41300000e+03 -1.05831156e+05  4.40000000e+01]]

 [[ 1.23700000e+03 -8.85970312e+04  4.40000000e+01]
  [ 8.66000000e+02 -5.46516250e+04  4.40000000e+01]
  [ 1.27700000e+03 -9.24573281e+04  4.40000000e+01]
  [ 1.41100000e+03 -1.05631828e+05  4.40000000e+01]
  [ 1.23300000e+03 -8.82129375e+04  4.40000000e+01]]

 ...

 [[ 1.02900000e+03 -6.91190000e+04  4.40000000e+01]
  [ 1.36600000e+03 -1.01167234e+05  4.40000000e+01]
  [ 8.47000000e+02 -5.30176562e+04  4.40000000e+01]
  [ 1.38100000e+03 -1.02651031e+05  4.40000000e+01]


[[[ 9.90000000e+02 -8.33830547e+04  6.50000000e+01]
  [ 4.07000000e+02 -2.73629062e+04  6.50000000e+01]
  [ 4.75000000e+02 -3.29295391e+04  6.50000000e+01]
  [ 1.82300000e+03 -1.85226469e+05  6.50000000e+01]
  [ 1.05800000e+03 -9.09228594e+04  6.50000000e+01]]

 [[ 1.89600000e+03 -1.94959562e+05  6.50000000e+01]
  [ 1.81000000e+03 -1.83504594e+05  6.50000000e+01]
  [ 1.25600000e+03 -1.13778672e+05  6.50000000e+01]
  [ 1.79100000e+03 -1.80994406e+05  6.50000000e+01]
  [ 1.01300000e+03 -8.59142031e+04  6.50000000e+01]]

 [[ 3.32000000e+02 -2.16088066e+04  6.50000000e+01]
  [ 6.92000000e+02 -5.25798828e+04  6.50000000e+01]
  [ 1.70400000e+03 -1.69598281e+05  6.50000000e+01]
  [ 1.79400000e+03 -1.81390219e+05  6.50000000e+01]
  [ 1.15500000e+03 -1.01960344e+05  6.50000000e+01]]

 ...

 [[ 3.27000000e+02 -2.12409414e+04  6.50000000e+01]
  [ 4.24000000e+02 -2.87249727e+04  6.50000000e+01]
  [ 4.68000000e+02 -3.23422422e+04  6.50000000e+01]
  [ 1.26800000e+03 -1.15203641e+05  6.50000000e+01]


[[[ 1.66500000e+03 -9.50564688e+04  8.60000000e+01]
  [ 1.22600000e+03 -6.17371250e+04  8.60000000e+01]
  [ 9.41000000e+02 -4.25285000e+04  8.60000000e+01]
  [ 6.83000000e+02 -2.72537266e+04  8.60000000e+01]
  [ 7.26000000e+02 -2.96358203e+04  8.60000000e+01]]

 [[ 3.61000000e+02 -1.21202539e+04  8.60000000e+01]
  [ 9.55000000e+02 -4.34195859e+04  8.60000000e+01]
  [ 9.05000000e+02 -4.02643906e+04  8.60000000e+01]
  [ 6.96000000e+02 -2.79663125e+04  8.60000000e+01]
  [ 1.28600000e+03 -6.60438438e+04  8.60000000e+01]]

 [[ 1.50300000e+03 -8.22915625e+04  8.60000000e+01]
  [ 1.25200000e+03 -6.35929688e+04  8.60000000e+01]
  [ 1.41000000e+03 -7.52036250e+04  8.60000000e+01]
  [ 9.36000000e+02 -4.22116875e+04  8.60000000e+01]
  [ 1.36300000e+03 -7.16917812e+04  8.60000000e+01]]

 ...

 [[ 3.73000000e+02 -1.25799297e+04  8.60000000e+01]
  [ 1.27000000e+03 -6.48871406e+04  8.60000000e+01]
  [ 1.23700000e+03 -6.25203281e+04  8.60000000e+01]
  [ 8.45000000e+02 -3.65812031e+04  8.60000000e+01]


[[[ 1.70000000e+03 -1.10898812e+05  1.04000000e+02]
  [ 3.98000000e+02 -1.66172578e+04  1.04000000e+02]
  [ 1.87900000e+03 -1.26720500e+05  1.04000000e+02]
  [ 3.29000000e+02 -1.34401758e+04  1.04000000e+02]
  [ 5.91000000e+02 -2.70923125e+04  1.04000000e+02]]

 [[ 1.16100000e+03 -6.65091094e+04  1.04000000e+02]
  [ 1.81900000e+03 -1.21364766e+05  1.04000000e+02]
  [ 1.12300000e+03 -6.35982188e+04  1.04000000e+02]
  [ 1.92300000e+03 -1.30680312e+05  1.04000000e+02]
  [ 6.81000000e+02 -3.25970000e+04  1.04000000e+02]]

 [[ 5.85000000e+02 -2.67377188e+04  1.04000000e+02]
  [ 1.22300000e+03 -7.13279844e+04  1.04000000e+02]
  [ 8.83000000e+02 -4.60457344e+04  1.04000000e+02]
  [ 1.38400000e+03 -8.42168594e+04  1.04000000e+02]
  [ 1.13200000e+03 -6.42846406e+04  1.04000000e+02]]

 ...

 [[ 1.17000000e+03 -6.72033594e+04  1.04000000e+02]
  [ 7.05000000e+02 -3.41200547e+04  1.04000000e+02]
  [ 1.73500000e+03 -1.13954891e+05  1.04000000e+02]
  [ 1.42900000e+03 -8.79097969e+04  1.04000000e+02]


[[[ 6.22000000e+02 -1.00148594e+04  1.26000000e+02]
  [ 9.61000000e+02 -3.74112344e+04  1.26000000e+02]
  [ 1.11600000e+03 -5.12379609e+04  1.26000000e+02]
  [ 9.68000000e+02 -3.80197500e+04  1.26000000e+02]
  [ 1.65400000e+03 -1.04336234e+05  1.26000000e+02]]

 [[ 8.50000000e+02 -2.79775469e+04  1.26000000e+02]
  [ 9.50000000e+02 -3.64581953e+04  1.26000000e+02]
  [ 1.21400000e+03 -6.03423516e+04  1.26000000e+02]
  [ 5.16000000e+02 -2.42677344e+03  1.26000000e+02]
  [ 1.57600000e+03 -9.61859531e+04  1.26000000e+02]]

 [[ 8.93000000e+02 -3.15829688e+04  1.26000000e+02]
  [ 3.73000000e+02  6.84438281e+03  1.26000000e+02]
  [ 6.96000000e+02 -1.56170781e+04  1.26000000e+02]
  [ 6.75000000e+02 -1.40035312e+04  1.26000000e+02]
  [ 1.60800000e+03 -9.95121094e+04  1.26000000e+02]]

 ...

 [[ 1.15100000e+03 -5.44584375e+04  1.26000000e+02]
  [ 8.97000000e+02 -3.19215625e+04  1.26000000e+02]
  [ 3.17000000e+02  1.01065938e+04  1.26000000e+02]
  [ 5.25000000e+02 -3.04939844e+03  1.26000000e+02]


[[[    638.           -6938.96875        146.        ]
  [    600.           -4635.2890625      146.        ]
  [   1684.          -88503.375          146.        ]
  [    401.            6283.25           146.        ]
  [    514.             335.6875         146.        ]]

 [[    703.          -11018.734375       146.        ]
  [   1319.          -56576.5625         146.        ]
  [   1564.          -77616.625          146.        ]
  [   1741.          -93808.6875         146.        ]
  [   1699.          -89891.1875         146.        ]]

 [[   1710.          -90912.6875         146.        ]
  [   1120.          -40660.5625         146.        ]
  [   1427.          -65655.0625         146.        ]
  [   1669.          -87121.625          146.        ]
  [    367.            7921.98828125     146.        ]]

 ...

 [[   1960.         -114991.375          146.        ]
  [   1867.         -105841.625          146.        ]
  [    595.           -4336.875          146.        

[[[   1905.         -117746.875          164.        ]
  [   1546.          -87144.34375        164.        ]
  [    724.          -29345.40625        164.        ]
  [   1572.          -89271.78125        164.        ]
  [    766.          -31756.9296875      164.        ]]

 [[    856.          -37154.6953125      164.        ]
  [   1537.          -86411.4375         164.        ]
  [   1009.          -47001.875          164.        ]
  [   1496.          -83095.46875        164.        ]
  [   1466.          -80693.53125        164.        ]]

 [[   1836.         -111669.9375         164.        ]
  [   1864.         -114125.375          164.        ]
  [    637.          -24583.0078125      164.        ]
  [   1827.         -110883.75           164.        ]
  [   1566.          -88779.53125        164.        ]]

 ...

 [[   1476.          -81491.90625        164.        ]
  [    813.          -34537.578125       164.        ]
  [   1899.         -117215.             164.        

[[[   1081.          -54982.265625       187.        ]
  [   1639.          -97782.0625         187.        ]
  [   1468.          -83952.765625       187.        ]
  [   1167.          -61115.234375       187.        ]
  [   1566.          -91807.453125       187.        ]]

 [[    573.          -23293.21875        187.        ]
  [   1533.          -89140.921875       187.        ]
  [   1136.          -58882.953125       187.        ]
  [   1795.         -110888.21875        187.        ]
  [    726.          -31892.0703125      187.        ]]

 [[    661.          -28122.             187.        ]
  [   1888.         -118912.484375       187.        ]
  [   1759.         -107823.78125        187.        ]
  [    748.          -33204.265625       187.        ]
  [   1088.          -55474.375          187.        ]]

 ...

 [[    369.          -13577.03515625     187.        ]
  [    938.          -45220.6328125      187.        ]
  [    399.          -14854.19140625     187.        

[[[   1024.          -83761.5546875      208.        ]
  [   1400.         -118963.390625       208.        ]
  [    488.          -38087.44140625     208.        ]
  [    315.          -25044.8671875      208.        ]
  [   1647.         -143120.484375       208.        ]]

 [[    669.          -52764.984375       208.        ]
  [    859.          -69039.03125        208.        ]
  [    517.          -40376.30078125     208.        ]
  [   1721.         -150495.53125        208.        ]
  [    830.          -66505.03125        208.        ]]

 [[    818.          -65461.48828125     208.        ]
  [    733.          -58157.25390625     208.        ]
  [   1500.         -128654.78125        208.        ]
  [   1821.         -160555.28125        208.        ]
  [   1825.         -160959.828125       208.        ]]

 ...

 [[    775.          -61746.85546875     208.        ]
  [   1338.         -113019.296875       208.        ]
  [    861.          -69214.40625        208.        

[[[    578.          -40104.55859375     225.        ]
  [   1086.          -91763.015625       225.        ]
  [   1849.         -182115.15625        225.        ]
  [   1275.         -113018.90625        225.        ]
  [   1214.         -106064.             225.        ]]

 [[    461.          -29813.53515625     225.        ]
  [    383.          -23415.00585938     225.        ]
  [    506.          -33679.72265625     225.        ]
  [   1572.         -148010.46875        225.        ]
  [    656.          -47369.46875        225.        ]]

 [[   1659.         -158580.734375       225.        ]
  [   1877.         -185632.859375       225.        ]
  [    702.          -51788.8515625      225.        ]
  [   1457.         -134252.15625        225.        ]
  [   1050.          -87817.75           225.        ]]

 ...

 [[   1466.         -135319.734375       225.        ]
  [   1056.          -88472.84375        225.        ]
  [   1802.         -176238.28125        225.        

[[[   1514.         -136804.71875        246.        ]
  [   1019.          -79537.9609375      246.        ]
  [   1724.         -163304.875          246.        ]
  [   1357.         -117788.8046875      246.        ]
  [   1056.          -83527.59375        246.        ]]

 [[   1440.         -127751.703125       246.        ]
  [   1204.          -99988.5703125      246.        ]
  [   1867.         -181977.9375         246.        ]
  [   1499.         -134957.0625         246.        ]
  [   1551.         -141389.0625         246.        ]]

 [[   1132.          -91882.734375       246.        ]
  [    406.          -22766.9765625      246.        ]
  [   1181.          -97379.625          246.        ]
  [    584.          -37111.375          246.        ]
  [   1617.         -149658.46875        246.        ]]

 ...

 [[   1041.          -81903.875          246.        ]
  [   1336.         -115301.296875       246.        ]
  [   1673.         -156764.40625        246.        

[[[   804.         -33155.125         268.        ]
  [   911.         -39582.15625       268.        ]
  [   359.         -11648.0625        268.        ]
  [  1263.         -63277.2578125     268.        ]
  [  1176.         -57092.59375       268.        ]]

 [[   484.         -16685.18359375    268.        ]
  [  1265.         -63421.7578125     268.        ]
  [   402.         -13274.09570312    268.        ]
  [  1059.         -49101.4296875     268.        ]
  [   560.         -20173.11328125    268.        ]]

 [[  1171.         -56743.2421875     268.        ]
  [   901.         -38964.578125      268.        ]
  [   896.         -38657.046875      268.        ]
  [   522.         -18392.17578125    268.        ]
  [   367.         -11941.49902344    268.        ]]

 ...

 [[  1183.         -57582.8046875     268.        ]
  [   674.         -25924.70703125    268.        ]
  [   981.         -43998.0546875     268.        ]
  [  1014.         -46134.3203125     268.        ]


[[[  1075.         -11191.0625        288.        ]
  [  1404.         -36037.65625       288.        ]
  [   703.          13583.8828125     288.        ]
  [   845.           4610.21875       288.        ]
  [  1715.         -61534.75          288.        ]]

 [[  1999.         -86242.3125        288.        ]
  [  1482.         -42262.734375      288.        ]
  [  1995.         -85886.125         288.        ]
  [  1561.         -48686.46875       288.        ]
  [  1109.         -13644.46875       288.        ]]

 [[  1769.         -66136.84375       288.        ]
  [  1401.         -35800.609375      288.        ]
  [  1344.         -31331.578125      288.        ]
  [  1250.         -24109.703125      288.        ]
  [  1701.         -60349.53125       288.        ]]

 ...

 [[   916.           -111.5625        288.        ]
  [  1085.         -11909.71875       288.        ]
  [   758.          10186.6484375     288.        ]
  [   981.          -4559.828125      288.        ]


[[[   1030.          -73167.             311.        ]
  [    808.          -53324.4921875      311.        ]
  [    683.          -42927.7578125      311.        ]
  [   1527.         -122629.             311.        ]
  [   1855.         -158368.609375       311.        ]]

 [[   1817.         -154116.40625        311.        ]
  [    635.          -39107.4765625      311.        ]
  [    673.          -42123.546875       311.        ]
  [   1120.          -81647.0703125      311.        ]
  [    782.          -51111.7734375      311.        ]]

 [[    602.          -36541.57421875     311.        ]
  [   1718.         -143172.203125       311.        ]
  [   1701.         -141312.78125        311.        ]
  [    437.          -24552.49609375     311.        ]
  [   1473.         -116964.1484375      311.        ]]

 ...

 [[    353.          -19087.19140625     311.        ]
  [   1541.         -124108.2265625      311.        ]
  [    889.          -60374.4140625      311.        

[[[   574.         -20281.6875        330.        ]
  [   589.         -21013.28125       330.        ]
  [   415.         -13274.734375      330.        ]
  [   393.         -12425.0390625     330.        ]
  [   305.          -9371.5703125     330.        ]]

 [[   379.         -11901.36328125    330.        ]
  [   482.         -16051.296875      330.        ]
  [   620.         -22560.078125      330.        ]
  [   303.          -9309.1484375     330.        ]
  [   890.         -37790.171875      330.        ]]

 [[   676.         -25468.25          330.        ]
  [   459.         -15067.375         330.        ]
  [   336.         -10380.48828125    330.        ]
  [   836.         -34513.1953125     330.        ]
  [   535.         -18433.03515625    330.        ]]

 ...

 [[   643.         -23737.140625      330.        ]
  [   419.         -13432.6484375     330.        ]
  [   864.         -36199.0546875     330.        ]
  [   779.         -31172.890625      330.        ]


[[[   316.            225.9453125     353.        ]
  [   312.            354.58203125    353.        ]
  [   344.           -708.6875        353.        ]
  [  1798.         -93083.09375       353.        ]
  [  1114.         -41625.609375      353.        ]]

 [[  1139.         -43301.953125      353.        ]
  [  1296.         -54209.5           353.        ]
  [   575.         -10316.6875        353.        ]
  [   970.         -32315.609375      353.        ]
  [  1872.         -99290.28125       353.        ]]

 [[   418.          -3444.0234375     353.        ]
  [  1044.         -37024.828125      353.        ]
  [  1750.         -89120.            353.        ]
  [  1147.         -43841.984375      353.        ]
  [   435.          -4122.15625       353.        ]]

 ...

 [[  1512.         -70222.9375        353.        ]
  [   711.         -17225.3671875     353.        ]
  [   332.           -300.91015625    353.        ]
  [  1268.         -52217.375         353.        ]


[[[   1591.         -104453.40625        370.        ]
  [   1102.          -62139.515625       370.        ]
  [   1638.         -108796.21875        370.        ]
  [   1152.          -66195.53125        370.        ]
  [   1004.          -54399.375          370.        ]]

 [[   1515.          -97523.765625       370.        ]
  [    821.          -40773.921875       370.        ]
  [    860.          -43579.53125        370.        ]
  [    608.          -26530.890625       370.        ]
  [    393.          -14359.0703125      370.        ]]

 [[    801.          -39357.3671875      370.        ]
  [    911.          -47331.28125        370.        ]
  [   1055.          -58391.734375       370.        ]
  [    401.          -14763.75           370.        ]
  [    716.          -33513.6015625      370.        ]]

 ...

 [[    461.          -17928.0546875      370.        ]
  [   1159.          -66768.859375       370.        ]
  [   1388.          -86214.203125       370.        

ValueError: num_samples should be a positive integer value, but got num_samples=0