In [6]:
from Neural_Nets.Classification.ThermoClassifier.Development.ThermoClassifier import ThermoClassifier
from Neural_Nets.Classification.ClassificationDataset.Development.ClassificationDataset import *
from torch.utils.data import DataLoader
import torch
import numpy as np

In [2]:
net = ThermoClassifier()

inp = torch.tensor([[[200., 5.]], [[250., 7.]], [[400., 50.]]])

print(inp.shape)

out = net(inp)
print(out.shape)
print(out)

torch.Size([3, 1, 2])
torch.Size([1, 5])
tensor([[0.2244, 0.2026, 0.1710, 0.1913, 0.2107]], grad_fn=<SoftmaxBackward0>)


C:\Users\danie\anaconda3\envs\5_Programmcodes\lib\site-packages\torch\nn\modules\container.py:141: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)


In [4]:
phase_dataset = ElementDataset((0, 5), 'Fe')

Fe successfully selected!

(302, 5, 3)
[[[ 4.40000000e+02 -1.27620938e+04  0.00000000e+00]
  [ 1.38700000e+03 -7.13308125e+04  0.00000000e+00]
  [ 1.21900000e+03 -5.80629766e+04  0.00000000e+00]
  [ 1.33300000e+03 -6.69729453e+04  0.00000000e+00]
  [ 1.73200000e+03 -1.01013125e+05  0.00000000e+00]]

 [[ 7.85000000e+02 -2.90583008e+04  0.00000000e+00]
  [ 6.35000000e+02 -2.11977734e+04  0.00000000e+00]
  [ 1.80800000e+03 -1.07944602e+05  0.00000000e+00]
  [ 1.34500000e+03 -6.79340078e+04  0.00000000e+00]
  [ 9.04000000e+02 -3.60851328e+04  0.00000000e+00]]

 [[ 6.40000000e+02 -2.14414727e+04  0.00000000e+00]
  [ 5.12000000e+02 -1.56241309e+04  0.00000000e+00]
  [ 9.43000000e+02 -3.85411055e+04  0.00000000e+00]
  [ 5.72000000e+02 -1.82399668e+04  0.00000000e+00]
  [ 7.59000000e+02 -2.76156016e+04  0.00000000e+00]]

 ...

 [[ 8.03000000e+02 -2.31538203e+04  4.00000000e+00]
  [ 6.23000000e+02 -1.22979922e+04  4.00000000e+00]
  [ 6.27000000e+02 -1.25240781e+04  4.00000000e+00]
  [ 1.0840000