In [29]:
import torch
import torch.autograd as autograd

In [23]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

In [24]:
Q = 3*a**3 - b**2

In [25]:
print(Q)

tensor([-12.,  65.], grad_fn=<SubBackward0>)


In [20]:
print(9*a**2 == a.grad)
print(-2*b == b.grad)

tensor([True, True])
tensor([True, True])


In [27]:
print(a.grad)

tensor([72., 81.])


In [46]:
v = a ** 2 + 2
y = v ** 2

print(v)
print(y)

dy_da = autograd.grad(outputs=y, inputs=a, grad_outputs=torch.ones_like(y))
print(f'dy/da:\n {dy_da}')

tensor([ 6., 11.], grad_fn=<AddBackward0>)
tensor([ 36., 121.], grad_fn=<PowBackward0>)
dy/da:
 (tensor([ 48., 132.]),)
False
