In [1]:
from thermoclassifier.elements.ensemble import EnsembleClassifierNet, majority_vote
from thermoclassifier.dataset.dataset_creator import DatasetCreator
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader

In [2]:
dc = DatasetCreator(elements=['Fe'],  splits=(0.8, 0.2), validation=False, seq_len=2, measurement='C', stable_only=True)
train_dataset, test_dataset, val_dataset = dc.get_datasets()
train_loader = DataLoader(train_dataset, batch_size=1, shuffle=True)

0 (603, 2, 3)
0 (603, 2, 3)
(603, 2, 3)


In [4]:
print(len(train_loader), len(train_dataset))

for d in train_loader:
    print(d)

603 603
tensor([[[462.0000,  28.4836,   0.0000],
         [700.0000,  35.0981,   0.0000]]], dtype=torch.float64)
tensor([[[632.0000,  32.8657,   0.0000],
         [863.0000,  42.5620,   0.0000]]], dtype=torch.float64)
tensor([[[1677.0000,   40.3674,    0.0000],
         [1757.0000,   40.9300,    0.0000]]], dtype=torch.float64)
tensor([[[469.0000,  28.6411,   0.0000],
         [789.0000,  38.6896,   0.0000]]], dtype=torch.float64)
tensor([[[698.0000,  35.0270,   0.0000],
         [972.0000,  51.0762,   0.0000]]], dtype=torch.float64)
tensor([[[ 921.0000,   46.5179,    0.0000],
         [1797.0000,   41.2359,    0.0000]]], dtype=torch.float64)
tensor([[[ 838.0000,   41.1352,    0.0000],
         [1021.0000,   56.9638,    0.0000]]], dtype=torch.float64)
tensor([[[1343.0000,   35.3089,    0.0000],
         [1770.0000,   41.0278,    0.0000]]], dtype=torch.float64)
tensor([[[1045.0000,   51.7292,    0.0000],
         [1492.0000,   36.5943,    0.0000]]], dtype=torch.float64)
tensor([[[1574.00

tensor([[[ 999.0000,   54.0915,    0.0000],
         [1210.0000,   34.1695,    0.0000]]], dtype=torch.float64)
tensor([[[1193.0000,   34.0242,    0.0000],
         [1415.0000,   35.9287,    0.0000]]], dtype=torch.float64)
tensor([[[1286.0000,   34.8198,    0.0000],
         [1776.0000,   41.0735,    0.0000]]], dtype=torch.float64)
tensor([[[454.0000,  28.3051,   0.0000],
         [926.0000,  46.9121,   0.0000]]], dtype=torch.float64)
tensor([[[806.0000,  39.4920,   0.0000],
         [867.0000,  42.8037,   0.0000]]], dtype=torch.float64)
tensor([[[ 751.0000,   37.0438,    0.0000],
         [1197.0000,   34.0584,    0.0000]]], dtype=torch.float64)
tensor([[[1114.0000,   44.6332,    0.0000],
         [1223.0000,   34.2806,    0.0000]]], dtype=torch.float64)
tensor([[[ 398.0000,   27.0869,    0.0000],
         [1628.0000,   37.7775,    0.0000]]], dtype=torch.float64)
tensor([[[ 879.0000,   43.5535,    0.0000],
         [1488.0000,   36.5596,    0.0000]]], dtype=torch.float64)
tensor([[[ 41

tensor([[[ 346.0000,   25.9593,    0.0000],
         [1130.0000,   43.7298,    0.0000]]], dtype=torch.float64)
tensor([[[ 604.0000,   32.0427,    0.0000],
         [1347.0000,   35.3433,    0.0000]]], dtype=torch.float64)
tensor([[[ 570.0000,   31.1060,    0.0000],
         [1179.0000,   41.8028,    0.0000]]], dtype=torch.float64)
tensor([[[ 872.0000,   43.1115,    0.0000],
         [1230.0000,   34.3404,    0.0000]]], dtype=torch.float64)
tensor([[[1330.0000,   35.1973,    0.0000],
         [1779.0000,   41.0965,    0.0000]]], dtype=torch.float64)
tensor([[[1147.0000,   42.9393,    0.0000],
         [1656.0000,   38.0224,    0.0000]]], dtype=torch.float64)
tensor([[[663.0000,  33.8388,   0.0000],
         [967.0000,  50.5699,   0.0000]]], dtype=torch.float64)
tensor([[[1232.0000,   34.3575,    0.0000],
         [1800.0000,   41.2594,    0.0000]]], dtype=torch.float64)
tensor([[[1129.0000,   43.7813,    0.0000],
         [1618.0000,   37.6901,    0.0000]]], dtype=torch.float64)
tensor(