In [1]:
from thermoclassifier.dataset.dataset_creator import DatasetCreator
import numpy as np

In [2]:
dc = DatasetCreator(elements=['Fe'],  splits=(0.8, 0.2), validation=False, seq_len=5, stable_only=True)

[[  1223.         -58396.83984375      0.        ]
 [  1705.         -98583.1484375       0.        ]
 [  1047.         -45480.0234375       0.        ]
 [  1493.         -80187.15625         0.        ]
 [  1416.         -73780.5625          0.        ]]
----------
[[  1047.         -45480.0234375       0.        ]
 [  1223.         -58396.83984375      0.        ]
 [  1416.         -73780.5625          0.        ]
 [  1493.         -80187.15625         0.        ]
 [  1705.         -98583.1484375       0.        ]]


In [3]:
a = np.array([[[9, 2, 3],
           [4, 5, 6],
           [7, 0, 5]], 
           [[19, 81, 30],
           [42, 56, 36],
           [79, 20, 15]]])
print(a)
print(a.shape)

[[[ 9  2  3]
  [ 4  5  6]
  [ 7  0  5]]

 [[19 81 30]
  [42 56 36]
  [79 20 15]]]
(2, 3, 3)


In [4]:
s = a[:, :, 1].argsort()
print(s)
print(s.shape)

b = a[:, a[:, :, 1].argsort()][np.diag_indices(2)]
print(b)
print(b.shape)

[[2 0 1]
 [2 1 0]]
(2, 3)
[[[ 7  0  5]
  [ 9  2  3]
  [ 4  5  6]]

 [[79 20 15]
  [42 56 36]
  [19 81 30]]]
(2, 3, 3)
